### ISSUE TITLE
rate limit errors

### ISSUE THREAD

**Issue by 573** [nix-community/cache-nix-action#11]
Using the action [here](https://github.com/573/nix-config-1/commit/c3e4b0299391b3e1cdd0ed2f1f0819d5814f0f5a#diff-d75c2041e682ae676b9b823aab6bdf33229f4a7027e93ac39fdd42a1ce7069fb) I get rate limit errors in the end, see [here](https://github.com/573/nix-config-1/actions/runs/5948575959/job/16132631411).

**Comment by 573** [comment]
This was the solution.
In case one wants to push artifacts generated via gha to cachix do you think this would be achievable paired with cache-nix-action ?

**Comment by deemp** [comment]
What's an artifact in this case?

A cache produced by cache-nix-action isn't an artifact.
Such a cache contains the whole nix store.
You can [push the whole store](https://docs.cachix.org/pushing#pushing-whole-nix-store) to cachix.
