### ISSUE TITLE
Updating to node 20 from 16

### ISSUE THREAD

**Issue by chandraaditya** [nix-community/cache-nix-action#28]
I'm getting this warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: nix-community/cache-nix-action@v5.0.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Is there any updated branch/tag that we can use?

**Comment by chandraaditya** [comment]
@deemp when can we expect to see a new release?

**Comment by deemp** [comment]
I will make one this evening. Any other suggestions?

**Comment by deemp** [comment]
I need more time.

**Comment by chandraaditya** [comment]
No problem, take your time. And nope, have no other suggestions for now. :)

**Comment by deemp** [comment]
@chandraaditya, updated the node version and released the new action version.

**Comment by chandraaditya** [comment]
@deemp thank you for that!
